import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { identity } from "@/content/identity";
import { fr } from "@/content/i18n/fr";
import { AppProvider } from "@/lib/providers";
import "./globals.css";

const plexSans = localFont({
  src: [
    { path: "../fonts/ibm-plex-sans-latin-400-normal.woff2", weight: "400", style: "normal" },
    { path: "../fonts/ibm-plex-sans-latin-600-normal.woff2", weight: "600", style: "normal" },
    { path: "../fonts/ibm-plex-sans-latin-700-normal.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-plex-sans",
  display: "swap",
});

const plexMono = localFont({
  src: [{ path: "../fonts/ibm-plex-mono-latin-400-normal.woff2", weight: "400", style: "normal" }],
  variable: "--font-plex-mono",
  display: "swap",
  // Only used for small labels in the 3D view; not worth a preload on mobile.
  preload: false,
});

export const metadata: Metadata = {
  metadataBase: new URL(identity.siteUrl),
  title: fr.meta.title,
  description: fr.meta.description,
  applicationName: "Mohamed Reda Karrach",
  authors: [{ name: identity.name, url: identity.github }],
  keywords: [
    "cybersécurité",
    "cybersecurity",
    "SOC",
    "Blue Team",
    "réponse à incident",
    "pentest",
    "Wazuh",
    "TheHive",
    "MITRE ATT&CK",
    "Casablanca",
    "stage PFE",
  ],
  alternates: { canonical: "/" },
  openGraph: {
    type: "profile",
    locale: "fr_MA",
    alternateLocale: ["en_GB"],
    url: identity.siteUrl,
    siteName: identity.name,
    title: fr.meta.title,
    description: fr.meta.description,
    firstName: "Mohamed Reda",
    lastName: "Karrach",
    username: identity.githubHandle,
  },
  twitter: {
    card: "summary_large_image",
    title: fr.meta.title,
    description: fr.meta.description,
  },
  robots: { index: true, follow: true },
  other: { "color-scheme": "dark light" },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0b1620" },
    { media: "(prefers-color-scheme: light)", color: "#f6f8fa" },
  ],
  width: "device-width",
  initialScale: 1,
};

/**
 * Applies the stored theme and language before hydration so the first paint
 * already has the right colours (no flash). Its SHA-256 hash is part of the
 * Content-Security-Policy generated by scripts/csp-hashes.mjs.
 */
const bootScript = `(function(){try{var d=document.documentElement;d.classList.add("js");var m=localStorage.getItem("rk-theme");if(m!=="dark"&&m!=="light"){m=matchMedia("(prefers-color-scheme: light)").matches?"light":"dark"}d.dataset.theme=m;var l=localStorage.getItem("rk-lang");if(l==="en"||l==="fr"){d.lang=l}}catch(e){}})();`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="fr"
      className={`${plexSans.variable} ${plexMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: bootScript }} />
      </head>
      <body className="min-h-dvh">
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
